@baseUrl = http://localhost:3000

### inventory Product

###
# @name inventoryProductGetAll
GET {{baseUrl}}/inventory-product

###
# @name inventoryProductGetOne
GET {{baseUrl}}/inventory-product/69cbe2736f4f01e78e83c3f8

###
# @name inventoryProductGetAllPerStatus
GET {{baseUrl}}/inventory-product/id122344/perStatus

###
# @name inventoryProductPost
POST {{baseUrl}}/inventory-product
Content-Type: application/json

{
  "name": "box",
  "price": 3600,
  "code": "codeOfProduct78"
}

###
# @name inventoryProductDelete
DELETE  {{baseUrl}}/inventory-product/69d30651c76d2a4a07de17cb

###
# @name inventoryProductPatch
PATCH  {{baseUrl}}/inventory-product/69cbf8c78638337c910bee74
Content-Type: application/json

{
  "status": "RESERVED"
}


### service orde

###
# @name serviceOrderPost
POST {{baseUrl}}/order/buyProduct
Content-Type: application/json

{
  "idProduct": "69cbf8c78638337c910bee74"
}