services:
  # INFRA
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - flowpay-network

  mongo-inventory:
    image: mongo:latest
    container_name: mongo-inventory
    ports:
      - "27017:27017"
    volumes:
      - mongo_inventory_data:/data/db
    networks:
      - flowpay-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  # MICROSERVICES
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway-local
    restart: always
    ports:
      - "8080:3000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - rabbitmq
    networks:
      - flowpay-network

  inventory-product:
    build:
      context: ./inventory-product
      dockerfile: Dockerfile
    container_name: inventory-product
    restart: always
    env_file:
      - ./inventory-product/.env
    depends_on:
      - rabbitmq
      - mongo-inventory
    networks:
      - flowpay-network

# PERSISTENCE DATA
volumes:
  rabbitmq_data:
  mongo_inventory_data:

networks:
  flowpay-network:
    driver: bridge
    