services:
  # INFRA
  rabbitmq:
    build:
      context: ./rabbitmq-custom
      dockerfile: Dockerfile
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: flowPay
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - flowpay-network

  mongo-inventory:
    image: mongo:latest
    container_name: mongo-inventory
    ports:
      - "27017:27017"
    volumes:
      - mongo_inventory_data:/data/db
    networks:
      - flowpay-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-payment:
    image: mongo:latest
    container_name: mongo-payment
    ports:
      - "27018:27017"
    volumes:
      - mongo_payment_data:/data/db
    networks:
      - flowpay-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-order:
    image: mongo:latest
    container_name: mongo-order
    ports:
      - "27019:27017"
    volumes:
      - mongo_order_data:/data/db
    networks:
      - flowpay-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  # MICROSERVICES
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway-local
    restart: always
    ports:
      - "8080:3000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - rabbitmq
    networks:
      - flowpay-network

  inventory-product:
    build:
      context: ./inventory-product
      dockerfile: Dockerfile
    container_name: inventory-product
    restart: always
    env_file:
      - ./inventory-product/.env
    depends_on:
      - rabbitmq
      - mongo-inventory
    networks:
      - flowpay-network

  service-payment:
    build:
      context: ./service-payment
      dockerfile: Dockerfile
    container_name: service-payment
    restart: always
    env_file:
      - ./service-payment/.env
    depends_on:
      - rabbitmq
      - mongo-payment
    networks:
      - flowpay-network

  service-order:
    build:
      context: ./service-order
      dockerfile: Dockerfile
    container_name: service-order
    restart: always
    env_file:
      - ./service-order/.env
    depends_on:
      - rabbitmq
      - mongo-order
    networks:
      - flowpay-network

# PERSISTENCE DATA
volumes:
  rabbitmq_data:
  mongo_inventory_data:
  mongo_payment_data:
  mongo_order_data:

networks:
  flowpay-network:
    driver: bridge
    